### ISSUE TITLE
Support to run application with sudo

### ISSUE THREAD

**Issue by chadjriddle** [GordianDotNet/VSMonoDebugger#1]
I am attempting to use VSMonoDebugger in conjunction with Unosquare.RaspberryIO and a Raspberry Pi. However, RaspberryIO requires the application to be run with sudo in order to have all the correct privileges. 

Is there a way to configure VSMonoDebugger to launch the debug session using sudo?

**Comment by chadjriddle** [comment]
Just forked the latest code and rebuilt the extension with the changes made for the Debug Scripts.  I am able to run with the sudo command and get full access the the Raspberry Pi.

Thanks for the great plugin.

**Comment by TheColonel2688** [comment]
chadjriddle could you elaborate on how you got this to work? I am trying it, it doesn't seem to be doing anything the debug session never opens

**Comment by GordianDotNet** [comment]
Since version 0.7.5 "sudo" can be added under "Debug scripts".

**Comment by GordianDotNet** [comment]
Pre-Debug script: 

```
sudo kill $(lsof -i | grep 'mono' | grep '\*:$(MONO_DEBUG_PORT)' | awk '{print $2}');
sudo kill $(ps w | grep '[m]ono --debugger-agent=address' | awk '{print $1}');`
```
- You can replace it with other kill commands like `pkill` (on my test embedded machine not available)

Debug script:

```
sudo mono --debugger-agent=address=0.0.0.0:$(MONO_DEBUG_PORT),transport=dt_socket,server=y --debug=mdb-optimizations $(TARGET_EXE_FILENAME) $(START_ARGUMENTS) &
```

- Test your debug scripts with a manual ssh session first 
Please replace parameters `$(MONO_DEBUG_PORT)  $(TARGET_EXE_FILENAME) $(START_ARGUMENTS) `with your application parameters!
Check if the process `mono --debugger-agent...` is running via `top`
- Test your debug script without mono debugger first
- Check your firewall settings with a simple C# program

See my comment on [X Server Support?](https://github.com/GordianDotNet/VSMonoDebugger/issues/3#issuecomment-415152574)
