### ISSUE TITLE
Remote Host IP: Is it okay if I put hostname .local here?

### ISSUE THREAD

**Issue by dhanarfmlx** [GordianDotNet/VSMonoDebugger#10]
I am using Windows 10 with Bonjour installed. I can ping and SSH my Raspberry Pi using their .local hostname.

When I deploy and debug (SSH) using VSMonoDebugger, if I put raspberrypi.local as Remote Host IP under VSMonoDebugger Settings, my program files is uploaded properly to Raspberry Pi. However, debug session on VS2017 seems to start and ended immediately. If I use the Raspberry Pi IP address, debug session can start normally.

It would be nice if we can use hostname as finding IP address each and every time is tedious.

Thanks.

PS. There is a chance that if I use raspberrypi.local, the IP address returned is IPv6 instead of IPv4. Is IPv6 supported?

**Comment by GordianDotNet** [comment]
I tested it via a entry in the hosts file. Dns.GetHostAddresses returns an array of the IPv6 and IPv4 address. IPv6 is not supported by mono soft debugger (I think?). I now always use the first IPv4 address.

Fixed in Version 0.9.0
