### ISSUE TITLE
Conditional compilation symbols not used when building with extension

### ISSUE THREAD

**Issue by nicorac** [GordianDotNet/VSMonoDebugger#14]
I have a source file shared between more than a project in the same solution.
The file contains some `#if` blocks to activate features based on the project containing it:
```C#
#if FOO
class Bar {
    ...
}
#endif
```
Each project needing the feature defines the symbol in its property dialog.

When I build the solution through menu Mono -> Build startup project with MDB files (but also other menu items have the same issue) the project is built without any symbol defined so that code is not built, throwing build errors...

**Comment by GordianDotNet** [comment]
I tested it in my project and it works fine.
I renamed a referenced class

```
#if MY_DEFINE
    public class ClassLibrary2Class1 : IService
#else
    public class ClassLibrary2Class1X : IService
#endif
```

Now I have to define MY_DEFINE under "Project/Properties/Build/Conditional compilation symbols".
And I have to do it for the selected Configuration of the start project (in my case Debug and Release).

I use the [SolutionBuild.BuildProject(String, String, Boolean)](https://docs.microsoft.com/en-us/dotnet/api/envdte.solutionbuild.buildproject?view=visualstudiosdk-2017) Method. So I don't see a additional option for conditional compilation symbols.

Which version of Visual Studio do you use?
Can you upload a very small test project to your github to test your problem?

**Comment by nicorac** [comment]
Sorry for the silence, I'm now back on the issue 😉

After some more investigation, it seems that the extension does not respect the solution Platform setting and it always use the first (default) platform configured.

To test it I've created solution with a sample project (VS2017):
https://github.com/nicorac/test-vsmonodebugger

It contains 2 platforms:
- Platform **AnyCPU**, with ANYCPU symbol defined (in both DEBUG and RELEASE)
- Platform **x86**, with X86 symbol defined (in both DEBUG and RELEASE)

Now select **x86** platform and
- build solution with **Build --> Build solution (CTRL+SHIFT+B)**: you'll get an assembly with `Console.WriteLine("X86");` in it (as expected)
- build solution with **Mono --> Build startup project with MDB files** (or any other Mono addin action): you'll get an assembly with `Console.WriteLine("ANYCPU");` code compiled in it, because the **X86** was defined

So build started with the addin always use the first platform defined and not the currently selected one.

I hope this helps you to fix the bug 😉

**Comment by GordianDotNet** [comment]
Thanks for the test project! With that the error was quickly found. Of course it is not written anywhere, but I could guess it from the *.csproj entry:
`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">`

I need to append the platform configuration to the SolutionBuild.BuildProject method with "|": 
`sb.BuildProject($"{activeConfigurationName}|{activeConfigurationPlatform}", startProject.FullName, true);`

Note: You have changed all configurations in the test project to the /bin folder. If a configuration (project or platform) is changed and there were no code changes and this configuration has already been built (exists in the /obj folder), the exe in the /bin folder is not overwritten. You must then trigger a rebuild.

**Comment by nicorac** [comment]
> Of course it is not written anywhere...

🤣

> Note: You have changed all configurations in the test project to the /bin folder.

Yep, I did it only to keep the sample as clean as possible.
I was analyzing the generated assembly with ILSpy, so having a single assembly made it easier (like just pressing the F5 in ILSpy to refresh it).

Thanks for the fix 👍
