### ISSUE TITLE
Don't work button from menu

### ISSUE THREAD

**Issue by Hromon** [GordianDotNet/VSMonoDebugger#16]
VS 2019 community v16.4.3
Version: 1.2.0 and 1.0.5

I try press any button, but he does not respond.

![2HKZoUhdhD](https://user-images.githubusercontent.com/29508584/73633926-f93c9500-4670-11ea-97f2-4db682443ca7.gif)

**Comment by GordianDotNet** [comment]
I'm sorry, but I don't know what that could be. Maybe install Visual Studio in English and try it out?

**Comment by Hromon** [comment]
Don't work.
Could it be that the plugin does not work due to the fact that my system drive has the name "H"?

**Comment by GordianDotNet** [comment]
Could be, but I don't know. Open Logfile doesn't work? 
You could try to get more information via [Visual Studio 2019 logs](https://devblogs.microsoft.com/visualstudio/troubleshooting-extensions-with-the-activity-log/).
