### ISSUE TITLE
When build startup project is pressed, the modified code not re-compiled sometimes

### ISSUE THREAD

**Issue by stevenmbiz** [GordianDotNet/VSMonoDebugger#18]
I tried to debug on my local windows 10 machine with Visual Studio 2017 so far no problems. But after I modified code and rebuild the project and then redeploy it, sometimes vs says copy files to deployment folder failed like the following:
             Couldn't copy/overwrite file 'D:\Documents\Mono\WindowsFormsApp1.exe'
which means maybe the mono.exe process still running, so would you please add a rebuild project option and stop the previous mono.exe instance before deployment? BTW this project really makes cross-platform development easier, thank you!

**Comment by GordianDotNet** [comment]
Actually this is already done via a Powershell script in the "Debug script" tab: 
See [README.md#settings-windows-local-machine](https://github.com/GordianDotNet/VSMonoDebugger/blob/master/README.md#settings-windows-local-machine)

`taskkill /IM mono.exe /F`

If it does not work in your case, you might have to adapt the script.
