### ISSUE TITLE
Extension Mono visible only when VS is started with administrator rights

### ISSUE THREAD

**Issue by krm2020** [GordianDotNet/VSMonoDebugger#23]
![This dialogue is not shown without VS started with admin rights](https://user-images.githubusercontent.com/73744562/114219665-3e421280-996b-11eb-95f3-de22d5624c45.jpg)
In Visual Studio 2019 the VSMonoDebugger extension is visible/accessible only when Visual Studio has been started with administrator rights. Starting VS with "normal" rights will not show up the dialogues for the debugger extension.

**Comment by krm2020** [comment]
Solution: install extension on the Windows command line manually using the /admin switch

**Comment by GordianDotNet** [comment]
Thank you for sharing your solution!
