### ISSUE TITLE
Cannot debug interactive command line programs?

### ISSUE THREAD

**Issue by wilstark** [GordianDotNet/VSMonoDebugger#24]
It appears there is no way to interact with a command line / console .NET app when debugging.  I'm using an embedded Linux target where the other debugger features work (deploy/run/breakpoints, etc), but it appears that there's no way to interact with a console style application via the debugger.  In particular stdin in not accessible.  (Stdout can be redirected to the Output windows in VS.)

**Comment by GordianDotNet** [comment]
Yes, for something like that you would have to start the debugger manually in a separate SSH session and then use the "Attach to mono debugger" menu item.

For a exe like `MonoDebuggerTest.exe` you have to start mono debugger like:
`mono --debugger-agent=address=0.0.0.0:11000,transport=dt_socket,server=y --debug=mdb-optimizations MonoDebuggerTest.exe`

Have a look in your output window. You should see the correct command for your application.
