### ISSUE TITLE
Deply, Run and Debug with error

### ISSUE THREAD

**Issue by Lucamenghini** [GordianDotNet/VSMonoDebugger#32]
Hi, thank you in advance.
When I launch "Deploy, run and debug" from VS "mono" menu I have this error:
"No startup project found! Checked projects in StartupProjects in ='iotTest01\iotTest01.vbproj' "
I have only 1 project in my solution and in the property everything appears ok about the startup option.
What I wrong?
thanks
bye

**Comment by GordianDotNet** [comment]
Sorry but you are using a Visual Basic project. The vbproj projects are different to C# projects. I don't have the time to support VB.
