### ISSUE TITLE
System.BadImageFormatException : Invalid directory size

### ISSUE THREAD

**Issue by kimbyungeun** [GordianDotNet/VSMonoDebugger#33]
Hello @GordianDotNet
It is very useful and well used in VS 2019. 
Thank you.

But in VS 2022 there is an issue.

## Visual Studio Version  
* Microsoft Visual Studio Professional 2022 (64-bit) - Current
* 17.3.5

## Extension Version 
* VSMonoDebugger2022 v2.2209.1806

## Error 
* No problem in VS 2019(VSMonoDebugger 1.5.1) with the same code.

![image](https://user-images.githubusercontent.com/18045312/194034823-3700596f-8bad-41f8-be38-2577ea68a08b.png)

**Comment by GordianDotNet** [comment]
Hi! I need a sample application that I can use to recreate this problem. Maybe the logs would be enough, but most of the time it is very difficult or impossible to find and fix such an error without a sample project.
