### ISSUE TITLE
Support embedded Mono

### ISSUE THREAD

**Issue by Liareth** [GordianDotNet/VSMonoDebugger#5]
Hi, I'm trying to get this to work with embedded Mono. I am able to connect but breakpoints do not hit. It seems `--debug=mdb-optimizations` is unrecognised when calling `mono_jit_parse_options()`, and all the documentation in the `mono_debug.h` header seems to indicate that mdb is now unsupported within Mono. I have tried calling `mono_debug_init()` with `MONO_DEBUG_FORMAT_DEBUGGER` but this crashes, again because mdb is no longer supported.

Do you have any experience with this, ways around it, or plans to support the soft debugger?

**Comment by Liareth** [comment]
For future reference, I got this working with the following code:

```c++
    if (remoteDebugging)
    {
        const char* opt[2] = 
        {
            "--debugger-agent=address=0.0.0.0:10000,transport=dt_socket,server=y",
            "--soft-breakpoints"
        };

        mono_jit_parse_options(2b, reinterpret_cast<char**>(&opt));
    }

    mono_debug_init(MONO_DEBUG_FORMAT_MONO);

    g_Domain = mono_jit_init("nwnx");
    mono_debug_domain_create(g_Domain);
```

You may need to manually convert the .pdb to .mdb by invoking `pdb2mdb <dll_path>` on your Linux machine. The conversion within this plugin seemed to mismatch so breakpoints were not being hit.

**Comment by GordianDotNet** [comment]
I need a small example program for embedded Mono to investigate this problem.

**Comment by GordianDotNet** [comment]
I was now able to test this case. In version 1.0.5 I have implemented a deployment for the local Windows machine.

To deploy and debug embedded mono code, the start scripts have to be adapted. You have to start your own application and pass the soft-debugger arguments as described above. The deployment path has to be adapted according to the requirements.
