### ISSUE TITLE
Exception when trying to debug an application

### ISSUE THREAD

**Issue by curia-damiano** [GordianDotNet/VSMonoDebugger#6]
Hi,
I have a .NET application running on an virtual machine with Debian 9.
For app requirements, it needs to start with "sudo mono MyApp.exe", so I log-in via SSH with root.
The plugin can deploy the app, and from the vm, I can start the app with sudo, as described above, without any problem.

If I try to attach to a running process, or I deploy&debug via SSH, I get the exception: "Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. occurred".

I would like to underline, the app starts perfectly when running it from command line, so it must be something related to the debugger.

Can you please help me?

**Comment by curia-damiano** [comment]
I would like to expand: on another very simple WinForm application (that again runs ok on Mono in Linux) I get an exception as soon as there is any call to WinForms.

Then I've developed a console application (again running ok on Mono on Linux) and the debugger works and is attached, but there is no UI on the Linux VM.
I have tried to set Redirect Output to None, but again I don't see any screen appearing.

So I definitely suppose that there are problems with the interaction with the screen, for both console and WinForms application.

Could you please give me some hints about how to deal with this?

**Comment by TheColonel2688** [comment]
Also may I susgest you switch to Avalonia? I only used Mono WinForms on my project because when I started it Avalonia didn't exist. Mono WinForms is legacy-ware at this point is and not well maintained.
https://github.com/AvaloniaUI/Avalonia

**Comment by curia-damiano** [comment]
Hi,
thank you for your help.
Currently Avalonia is not an option because the app is very big and already implemented with WinForms.
I'll try the scripts in issue #3 .

**Comment by curia-damiano** [comment]
Solved:
- use DISPLAY=:0 before running the mono command
- don't use the root login, as it doens't have X access)

**Comment by BarbaSoft** [comment]
Great! using DISPLAY=:0 run !
Thank you
